lib/url_shortener_web/router.ex
defmodule URLShortenerWeb.Router do
  use URLShortenerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {URLShortenerWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", URLShortenerWeb do
    pipe_through :browser

    live "/", URLShortenerLive.Index, :index
    live "/stats", URLShortenerLive.Stats, :stats

    get "/:short_url", RedirectController, :redirect
  end

  # Other scopes may use custom stacks.
  scope "/api", URLShortenerWeb do
    pipe_through :api
    post "/gen_short_url", ShortURLGenController, :create
    post "/export", ExportController, :create
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  # if Mix.env() in [:dev, :test] do
  #   import Phoenix.LiveDashboard.Router
  #
  #   scope "/" do
  #     pipe_through :browser
  #
  #     live_dashboard "/dashboard", metrics: URLShortenerWeb.Telemetry
  #   end
  # end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  # if Mix.env() == :dev do
  #   scope "/dev" do
  #     pipe_through :browser
  #
  #     forward "/mailbox", Plug.Swoosh.MailboxPreview
  #   end
  # end
end

lib/url_shortener_web/live/url_shortener_live/index.ex
defmodule URLShortenerWeb.URLShortenerLive.Index do
  use URLShortenerWeb, :live_view

  alias URLShortener.URLStore
  alias URLShortener.URLStore.MappedURL

  @impl true
  def mount(_assigns, _session, socket) do
    {:ok, socket |> assign(:short_url, "")}
  end

  @impl true
  def handle_params(_unsigned_params, _uri, socket) do
    {:noreply, socket}
  end

  @impl true
  def handle_event(
        "generate_short_url",
        %{"short_url_form" => %{"url" => ""}},
        socket
      ) do
    {:noreply, socket}
  end

  @impl true
  def handle_event(
        "generate_short_url",
        %{"short_url_form" => %{"url" => url}},
        socket
      ) do
    {:ok, url = %MappedURL{}} = URLStore.create_mapped_url(%{long_url: url})

    {:noreply,
     socket
     |> assign(:short_url, url.short_url)
     |> put_flash(:info, "Your Short URL was generated")
     |> push_patch(to: Routes.url_shortener_index_path(socket, :index))}
  end
end

lib/url_shortener_web/live/url_shortener_live/stats.ex
defmodule URLShortenerWeb.URLShortenerLive.Stats do
  use URLShortenerWeb, :live_view
  alias URLShortener.URLStore

  @impl true
  def mount(_assigns, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(_unsigned_params, _uri, socket) do
    all_mapped_urls = URLStore.list_mapped_urls()

    {:noreply,
     socket
     |> assign(:all_mapped_urls, all_mapped_urls)}
  end
end

lib/url_shortener_web/live/url_shortener_live/index.html.heex
<div class="flex min-h-full flex-col justify-center py-12 sm:px-6 lg:px-8">
  <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
      <.form
        let={f}
        for={:short_url_form}
        id="short_url_gen_form"
        phx-submit="generate_short_url"
        class="space-y-6"
      >
        <%= label(f, "Plase Input Your URL:", class: "block font-bold uppercase text-gray-700") %>
        <%= url_input(f, :url,
          class:
            "block w-full appearance-none rounded-md border border-gray-300 px-3 py-2 placeholder-gray-400 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
        ) %>
        <%= error_tag(f, :url) %>

        <div>
          <%= submit("Generate Short URL",
            phx_disable_with: "Saving...",
            class:
              "flex w-full justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
          ) %>
        </div>
      </.form>
    </div>
    <%= if @short_url != "" do %>
      <div class="bg-white">
        <div class="mx-auto max-w-7xl py-16 px-4 sm:py-24 sm:px-6 lg:px-8">
          <div class="text-center">
            <h2 class="text-lg font-semibold">Your Short Link</h2>
            <%= link(System.get_env("HOST_NAME") <> @short_url,
              to: @short_url,
              class: "mx-auto mt-5 max-w-xl text-xl text-blue-500 underline"
            ) %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="flex min-h-full flex-col justify-center py-12 sm:px-6 lg:px-8">
      <%= link("Go to Stats",
        to: "/stats",
        class:
          "text-center rounded-md border border-transparent bg-indigo-600 px-6 py-3 text-base font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
      ) %>
    </div>
  </div>
</div>

lib/url_shortener_web/live/url_shortener_live/stats.html.heex
<div class="px-4 sm:px-6 lg:px-8">
  <div class="flex min-h-full flex-col justify-center py-12 sm:px-6 lg:px-8">
    <%= link("Back To Home",
      to: "/",
      class:
        "text-center w-64 rounded-md border border-transparent bg-indigo-600 px-6 py-3 text-base font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
    ) %>
  </div>
  <div class="flex justify-end mb-2">
    <%= link to: Routes.export_path(@socket, :create), class: "text-center w-64 rounded-md border border-transparent bg-indigo-600 px-6 py-3 text-base font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2", method: :post do %>
      Export CSV
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="currentColor"
        class="w-6 h-6 ml-1"
        viewBox="0 0 16 16"
      >
        <path
          fill-rule="evenodd"
          d="M14 4.5V14a2 2 0 0 1-2 2h-1v-1h1a1 1 0 0 0 1-1V4.5h-2A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v9H2V2a2 2 0 0 1 2-2h5.5L14 4.5ZM3.517 14.841a1.13 1.13 0 0 0 .401.823c.13.108.289.192.478.252.19.061.411.091.665.091.338 0 .624-.053.859-.158.236-.105.416-.252.539-.44.125-.189.187-.408.187-.656 0-.224-.045-.41-.134-.56a1.001 1.001 0 0 0-.375-.357 2.027 2.027 0 0 0-.566-.21l-.621-.144a.97.97 0 0 1-.404-.176.37.37 0 0 1-.144-.299c0-.156.062-.284.185-.384.125-.101.296-.152.512-.152.143 0 .266.023.37.068a.624.624 0 0 1 .246.181.56.56 0 0 1 .12.258h.75a1.092 1.092 0 0 0-.2-.566 1.21 1.21 0 0 0-.5-.41 1.813 1.813 0 0 0-.78-.152c-.293 0-.551.05-.776.15-.225.099-.4.24-.527.421-.127.182-.19.395-.19.639 0 .201.04.376.122.524.082.149.2.27.352.367.152.095.332.167.539.213l.618.144c.207.049.361.113.463.193a.387.387 0 0 1 .152.326.505.505 0 0 1-.085.29.559.559 0 0 1-.255.193c-.111.047-.249.07-.413.07-.117 0-.223-.013-.32-.04a.838.838 0 0 1-.248-.115.578.578 0 0 1-.255-.384h-.765ZM.806 13.693c0-.248.034-.46.102-.633a.868.868 0 0 1 .302-.399.814.814 0 0 1 .475-.137c.15 0 .283.032.398.097a.7.7 0 0 1 .272.26.85.85 0 0 1 .12.381h.765v-.072a1.33 1.33 0 0 0-.466-.964 1.441 1.441 0 0 0-.489-.272 1.838 1.838 0 0 0-.606-.097c-.356 0-.66.074-.911.223-.25.148-.44.359-.572.632-.13.274-.196.6-.196.979v.498c0 .379.064.704.193.976.131.271.322.48.572.626.25.145.554.217.914.217.293 0 .554-.055.785-.164.23-.11.414-.26.55-.454a1.27 1.27 0 0 0 .226-.674v-.076h-.764a.799.799 0 0 1-.118.363.7.7 0 0 1-.272.25.874.874 0 0 1-.401.087.845.845 0 0 1-.478-.132.833.833 0 0 1-.299-.392 1.699 1.699 0 0 1-.102-.627v-.495Zm8.239 2.238h-.953l-1.338-3.999h.917l.896 3.138h.038l.888-3.138h.879l-1.327 4Z"
        />
      </svg>
    <% end %>
  </div>
  <div class="mt-8 flex flex-col">
    <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                  Short URL
                </th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                  Long URL
                </th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                  Visited
                </th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 bg-white">
              <%= for url <- @all_mapped_urls do %>
                <tr>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                    <%= link(System.get_env("HOST_NAME") <> url.short_url, to: url.short_url) %>
                  </td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                    <%= url.long_url %>
                  </td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                    <%= url.visited %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>